include_guard(GLOBAL)

set(sel4_cmake_path "${CMAKE_CURRENT_LIST_DIR}")

macro(include_sel4_configuration config_path)
    include("${sel4_cmake_path}/configs/${config_path}.cmake")
endmacro()

macro(finalize_sel4_configuration)
    include(${sel4_cmake_path}/settings.cmake)
    add_subdirectory(${sel4_cmake_path}/sel4_core_setup)
    include(rootserver)
endmacro()

macro(finalize_sel4_build)
    if(SIMULATION)
        include(simulation)
        if(KernelSel4ArchX86_64)
            SetSimulationScriptProperty(MEM_SIZE "3G")
        endif()
        if(KernelPlatformQEMUArmVirt)
            SetSimulationScriptProperty(MEM_SIZE "2G")
        endif()
        GenerateSimulateScript()
    endif()
endmacro()